# brew 'rbenv'
# brew 'fnm'
# brew 'ruby-build'
# brew 'postgresql'
brew 'fd'
brew 'asdf'
brew 'difftastic'
brew 'ripgrep'
brew 'fzf'
brew 'neovim'
brew 'fish'
brew 'efm-langserver'
brew 'exa'
brew 'curl'
brew 'htop'
brew 'git'
brew 'starship'
brew 'tree-sitter'
brew 'zoxide'
brew 'yarn'
brew 'tmux'
brew 'lua-language-server'
brew 'bat'
brew 'redis'
brew 'git-delta'
brew 'less'
brew 'lefthook'
brew 'prettier'
brew 'entr'
brew 'jq'
brew 'yabai'
brew 'atuin'
brew 'tree'
brew 'ffmpeg'

tap 'natecraddock/taps'
brew 'zf'

tap 'homebrew/cask-fonts'
cask 'font-hack-nerd-font'

cask 'karabiner-elements'
cask 'bitwarden'
cask 'hammerspoon'
cask 'google-chrome'
cask 'slack'
cask 'betterdisplay'
cask 'kitty'
cask 'syncthing'
cask 'contexts'
cask 'bartender'

# vim:ft=ruby:
