format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

right_format = """
$cmd_duration\
$python\
$ruby\
$javascript\
"""

[directory]
style = "blue"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[>](bold purple)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "bold green"
conflicted = " "
untracked = " "
modified = " "
staged = " "
renamed = " "
deleted = " "
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[ruby]
format = "[$symbol($version)]($style) "
symbol = " "
