-- stylua: ignore
return {
  fillchars              = {
    diff                 = "╱",
    eob                  = " ",
  },
  lsp_kind               = {
    Text                 = " ",
    String               = " ",
    Method               = " ",
    Function             = " ",
    KeywordFunction      = " ",
    Constructor          = " ",
    Field                = " ",
    Variable             = " ",
    Class                = " ",
    Copilot              = " ",
    Interface            = " ",
    Module               = " ",
    Property             = " ",
    Unit                 = " ",
    Value                = " ",
    Enum                 = " ",
    Keyword              = " ",
    Snippet              = " ",
    Comment              = " ",
    Error                = " ",
    Color                = " ",
    File                 = " ",
    Reference            = " ",
    Folder               = " ",
    EnumMember           = " ",
    Constant             = " ",
    Struct               = " ",
    Event                = " ",
    Operator             = " ",
    TypeParameter        = " ",
    KeywordOperator      = " ",
    KeywordConditional   = " ",
    StringSpecialSymbol  = " ",
    VariableMember       = " ",
    Nospell              = " ",
    None                 = " ",
  },
  listchars              = {
    space                = " ",
    tab                  = " ",
    trail                = "•",
    extends              = "❯",
    precedes             = "❮",
    nbsp                 = "␣",
  },
  diagnostics            = {
    " ",
    " ",
    " ",
    " ",
    ERROR                = " ",
    WARNING              = " ",
    INFO                 = " ",
    HINT                 = " ",
    DEBUG                = " ",
    TRACE                = " ",
  },
  dap                    = {
    breakpoint           = " ",
    breakpoint_condition = " ",
    log_point            = " ",
    stopped              = " ",
    breakpoint_rejected  = " ",
    pause                = " ",
    play                 = " ",
    step_into            = " ",
    step_over            = " ",
    step_out             = " ",
    step_back            = " ",
    run_last             = " ",
    terminate            = " ",
  },
  git                    = {
    status_added         = " ",
    status_removed       = " ",
    status_modified      = " ",
    added                = " ",
    deleted              = " ",
    modified             = " ",
    renamed              = " ",
    untracked            = " ",
    ignored              = " ",
    unstaged             = " ",
    staged               = " ",
    conflict             = " ",
  },
  misc                   = {
    collapsed            = " ",
    expanded             = " ",
    current              = " ",
    folder_empty         = "",
    folder_closed        = "",
    folder_open          = "",
    file                 = "",
    v_border             = "▐",
    v_pipe               = "▎",
  },
}
