#!/usr/bin/env bash

# Disable system window manager
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# Try out: https://github.com/FelixKratz/yabai
# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement    second_child
yabai -m config window_opacity      off
yabai -m config window_shadow       off
yabai -m config split_ratio         0.50
yabai -m config auto_balance        off
yabai -m config mouse_modifier      fn
yabai -m config mouse_action1       move
yabai -m config mouse_action2       resize
yabai -m config layout              bsp
yabai -m config top_padding         2
yabai -m config bottom_padding      2
yabai -m config left_padding        3
yabai -m config right_padding       3
yabai -m config window_gap          3
yabai -m config window_shadow       float

yabai -m signal --add event=display_added   action="ruby ${HOME}/.config/yabai/display_added.rb"
yabai -m signal --add event=display_removed action="ruby ${HOME}/.config/yabai/display_added.rb"

# https://github.com/koekeishiya/yabai/issues/1471
yabai -m rule --add label=slack_huddle app="^Slack$" subrole!=AXStandardWindow

# https://github.com/FelixKratz/JankyBorders
# borders active_color=0xff98c379 inactive_color=0x00c792ea width=5.0 2>/dev/null 1>&2 &
