#!/usr/bin/env bash

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_opacity_duration      0.0
yabai -m config window_animation_duration    0.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config window_border                on
yabai -m config window_border_blur           on
yabai -m config window_border_hidpi          on
yabai -m config window_border_width          3
yabai -m config window_border_radius         9
yabai -m config normal_window_border_color   0x00c792ea
yabai -m config active_window_border_color   0xff98c379
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   1
yabai -m config window_shadow                float

yabai -m signal --add event=display_added action="ruby ${HOME}/.config/yabai/display_added.rb"
yabai -m signal --add event=display_removed action="ruby ${HOME}/.config/yabai/display_added.rb"
