---
include:
  - "**/*.rb"

exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
  - node_modules/**/*

require: []

domains: []

reporters:
  - rubocop

formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []

require_paths: []

plugins: []

max_files: 5000
