abbr -a -- - 'cd $PREV_CWD'
abbr -a -- b 'bundle'
abbr -a -- be 'bundle exec'
abbr -a -- bi 'brew install'
abbr -a -- bo 'brew outdated | fzf --multi --reverse | xargs brew upgrade'
abbr -a -- da 'direnv allow'
abbr -a -- disk 'ncdu'
abbr -a -- g 'git'
abbr -a -- gst 'git st'
abbr -a -- ls 'eza --color=always --icons --group-directories-first --all --long'
abbr -a -- magit 'emacs -nw -f magit'
abbr -a -- pro-dk 'KG_SITE=pro-dk'
abbr -a -- pro-se 'KG_SITE=pro-se'
abbr -a -- ra 'ls spec/**/*_spec.rb | entr -r -c bundle exec rspec /_'
abbr -a -- rc 'rails console'
abbr -a -- rdbm 'bundle exec rails db:migrate'
abbr -a -- rf 'bundle exec rspec --only-failures'
abbr -a -- rrf 'rails routes | fzf | awk \'{ print $1 "_path" }\' | tr -d "n" | pbcopy'
abbr -a -- rs 'bundle exec rspec'
abbr -a -- serve 'ruby -run -e httpd . -p 80'
abbr -a -- v 'nvim'
abbr -a -- autotest 'find ./spec -name "*_spec.rb" | entr -r -c bundle exec rspec /_ --format doc'

abbr -a -- oc 'overmind connect'
abbr -a -- oq 'overmind quit'
abbr -a -- oqf 'rm -f ./.overmind.sock'
abbr -a -- os 'overmind start -F ~/.config/tmux/overmind.tmux.conf'
abbr -a -- osd 'overmind start -D -F ~/.config/tmux/overmind.tmux.conf'
